export const EXPO_PUBLIC_SUPABASE_URL =
  "https://mrsocxnsrjnerueenelt.supabase.co";
export const EXPO_PUBLIC_SUPABASE_ANON_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1yc29jeG5zcmpuZXJ1ZWVuZWx0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mjc1MzIyNjgsImV4cCI6MjA0MzEwODI2OH0.Jc_IuL8LyKV5ufZF6tKRti5XlJWwynJkEPL2AT72J5g";
